# Generated by Django 6.0.1 on 2026-01-08 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidite', models.FloatField(help_text='Humidity in %')),
                ('air', models.FloatField(help_text='Air quality in ppm (equivalent MQ-135)')),
                ('bruit', models.FloatField(help_text='Noise level in dB')),
                ('luminosite', models.FloatField(help_text='Light level in lux')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the measurement')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Name of the room', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the room')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='IndiceConfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.FloatField(help_text='Global comfort score (0-100)')),
                ('statut', models.CharField(choices=[('comfort', 'Confortable'), ('warning', 'Moyen'), ('danger', 'Inconfortable')], help_text='Comfort status', max_length=10)),
                ('score_temperature', models.FloatField(help_text='Temperature score (0-100)')),
                ('score_humidite', models.FloatField(help_text='Humidity score (0-100)')),
                ('score_air', models.FloatField(help_text='Air quality score (0-100)')),
                ('score_bruit', models.FloatField(help_text='Noise score (0-100)')),
                ('score_luminosite', models.FloatField(help_text='Light score (0-100)')),
                ('timestamp', models.DateTimeField(help_text='Timestamp copied from the measurement')),
                ('mesure', models.OneToOneField(help_text='Associated measurement', on_delete=django.db.models.deletion.CASCADE, related_name='indice_confort', to='core.mesure')),
            ],
            options={
                'verbose_name': 'Indice de Confort',
                'verbose_name_plural': 'Indices de Confort',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('temperature', 'Température'), ('humidite', 'Humidité'), ('air', "Qualité de l'air"), ('bruit', 'Bruit'), ('luminosite', 'Luminosité')], help_text='Type of parameter that triggered the alert', max_length=20)),
                ('valeur', models.FloatField(help_text='Measured value')),
                ('seuil', models.FloatField(help_text='Threshold value')),
                ('niveau', models.CharField(choices=[('warning', 'Avertissement'), ('danger', 'Danger')], help_text='Alert level', max_length=10)),
                ('message', models.TextField(help_text='Alert message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the alert')),
                ('mesure', models.ForeignKey(help_text='Associated measurement', on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.mesure')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='mesure',
            name='salle',
            field=models.ForeignKey(help_text='Room where the measurement was taken', on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.salle'),
        ),
    ]
